config:
  credentials: []
  project_repos:
    git.man.poznan.pl/stash/scm/eosc-rs/preprocessor:
      branch: master
      repo: https://git.man.poznan.pl/stash/scm/eosc-rs/preprocessor.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-dandelion-burmese.sh
        container: qc.acc_snippy-auburn-terrier
  QC.Doc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-ruby-mist.sh
        container: qc.doc_shabby-sepia-skunk
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-charcoal-otter.sh
        container: qc.doc_wimpy-brass-uakari
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-zucchini-chinchilla.sh
        container: qc.doc_wimpy-mustard-wolverine
  QC.Lic:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-goldenrod-orangutan.sh
        container: qc.lic_squirrely-chartreuse-mandrill
  QC.Met:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-red-cat.sh
        container: qc.met_surly-brass-monkey
  QC.Sec:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-ultramarine-mayfly.sh
        container: qc.sec_snippy-red-harrier
  QC.Sty:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-razzmatazz-terrier.sh
        container: qc.sty_hasty-red-antelope
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor flake8:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-platinum-beaver.sh
        container: qc.sty_muggy-thistle-wasp
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-malachite-spaniel.sh
        container: qc.sty_leaky-ecru-lynx
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-auburn-cuscus.sh
        container: qc.sty_breezy-thistle-hummingbird
  QC.Ver:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-sepia-fossa.sh
        container: qc.ver_shaky-maroon-dalmatian
timeout: 5400
