config:
  credentials: []
  project_repos:
    git.man.poznan.pl/stash/scm/eosc-rs/preprocessor:
      branch: master
      repo: https://git.man.poznan.pl/stash/scm/eosc-rs/preprocessor.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-firebrick-alligator.sh
        container: qc.acc_craggy-salmon-russel
  QC.Doc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-silver-penguin.sh
        container: qc.doc_randy-orange-zorse
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-heliotrope-havanese.sh
        container: qc.doc_sickly-ultramarine-emu
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-linen-kangaroo.sh
        container: qc.doc_nippy-razzmatazz-bulldog
  QC.Lic:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-crimson-tapir.sh
        container: qc.lic_sickly-fuchsia-caracal
  QC.Ver:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-champagne-barracuda.sh
        container: qc.ver_leaky-cardinal-rat
timeout: 5400
