config:
  credentials: []
  project_repos:
    git.man.poznan.pl/stash/scm/eosc-rs/preprocessor:
      branch: master
      repo: https://git.man.poznan.pl/stash/scm/eosc-rs/preprocessor.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-wisteria-orangutan.sh
        container: qc.acc_stealthy-rust-harrier
  QC.Doc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-red-grasshopper.sh
        container: qc.doc_gummy-razzmatazz-dodo
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-saffron-setter.sh
        container: qc.doc_gummy-green-oyster
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-peach-wolverine.sh
        container: qc.doc_tasty-orchid-kakapo
  QC.Lic:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-lime-gerbil.sh
        container: qc.lic_queasy-silver-argentino
  QC.Met:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-pink-gibbon.sh
        container: qc.met_scanty-heliotrope-llama
  QC.Sec:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-cobalt-tiger.sh
        container: qc.sec_randy-eggplant-monster
  QC.Sty:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-violet-whippet.sh
        container: qc.sty_ugly-gold-scorpion
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor flake8:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-russet-koala.sh
        container: qc.sty_ready-cornflower-snail
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-ultramarine-saola.sh
        container: qc.sty_hasty-chestnut-sponge
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-turquoise-crocodile.sh
        container: qc.sty_scanty-cerulean-indri
  QC.Ver:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-taupe-seal.sh
        container: qc.ver_cozy-bronze-eleuth
timeout: 5400
