config:
  credentials: []
  project_repos:
    git.man.poznan.pl/stash/scm/eosc-rs/preprocessor:
      branch: master
      repo: https://git.man.poznan.pl/stash/scm/eosc-rs/preprocessor.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-xanthic-squirrel.sh
        container: qc.acc_queasy-flax-bandicoot
  QC.Doc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-magenta-quokka.sh
        container: qc.doc_lanky-chocolate-dalmatian
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-alizarin-catfish.sh
        container: qc.doc_pretty-malachite-serval
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-green-chipmunk.sh
        container: qc.doc_wimpy-russet-salamander
  QC.Lic:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-viridian-dragon.sh
        container: qc.lic_goopy-celadon-hare
  QC.Met:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-charcoal-snake.sh
        container: qc.met_grumpy-celadon-hornet
  QC.Sec:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-myrtle-hare.sh
        container: qc.sec_gloppy-azure-emu
  QC.Sty:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-tan-dragon.sh
        container: qc.sty_cranky-green-opossum
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-seashell-tuatara.sh
        container: qc.sty_sickly-bronze-tortoise
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-olivine-fish.sh
        container: qc.sty_freaky-scarlet-hummingbird
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-gold-centipede.sh
        container: qc.sty_whiny-olivine-cassowary
  QC.Ver:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-magnolia-urchin.sh
        container: qc.ver_chewy-celadon-zebu
timeout: 5400
