config:
  credentials: []
  project_repos:
    git.man.poznan.pl/stash/scm/eosc-rs/preprocessor:
      branch: master
      repo: https://git.man.poznan.pl/stash/scm/eosc-rs/preprocessor.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-cerulean-guppy.sh
        container: qc.acc_snazzy-green-harrier
  QC.Doc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-tangerine-iguana.sh
        container: qc.doc_crabby-seashell-discus
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-denim-hummingbird.sh
        container: qc.doc_lanky-bistre-caiman
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-asparagus-javanese.sh
        container: qc.doc_silly-flax-cheetah
  QC.Lic:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-ivory-bracke.sh
        container: qc.lic_gummy-burgundy-indri
  QC.Sty:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-ochre-argentino.sh
        container: qc.sty_squirrely-green-urchin
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-xanthic-wolfhound.sh
        container: qc.sty_leaky-silver-okapi
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-magenta-schnauzer.sh
        container: qc.sty_boozy-burgundy-camel
  QC.Ver:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/preprocessor get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-champagne-chinook.sh
        container: qc.ver_pokey-gamboge-wrasse
timeout: 5400
